export const sampleDFAs = [
  {
    id: 'strings-ending-ab',
    name: 'Strings ending with "ab"',
    description: 'A DFA that accepts all strings over {a, b} ending with "ab".',
    acceptedExamples: ['ab', 'aab', 'bab', 'aaab', 'bbab'],
    rejectedExamples: ['a', 'b', 'ba', 'aa', 'bb'],
    automaton: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      startState: 'q0',
      finalStates: ['q2'],
      transitions: [
        { from: 'q0', to: 'q1', symbol: 'a' },
        { from: 'q0', to: 'q0', symbol: 'b' },
        { from: 'q1', to: 'q1', symbol: 'a' },
        { from: 'q1', to: 'q2', symbol: 'b' },
        { from: 'q2', to: 'q1', symbol: 'a' },
        { from: 'q2', to: 'q0', symbol: 'b' },
      ],
    },
    positions: { q0: { x: 100, y: 200 }, q1: { x: 350, y: 200 }, q2: { x: 600, y: 200 } },
  },
  {
    id: 'even-zeros',
    name: 'Even number of 0s',
    description: 'Accepts strings over {0, 1} with an even number of 0s.',
    acceptedExamples: ['', '1', '00', '11', '001'],
    rejectedExamples: ['0', '01', '10', '000'],
    automaton: {
      states: ['q0', 'q1'],
      alphabet: ['0', '1'],
      startState: 'q0',
      finalStates: ['q0'],
      transitions: [
        { from: 'q0', to: 'q1', symbol: '0' },
        { from: 'q0', to: 'q0', symbol: '1' },
        { from: 'q1', to: 'q0', symbol: '0' },
        { from: 'q1', to: 'q1', symbol: '1' },
      ],
    },
    positions: { q0: { x: 150, y: 200 }, q1: { x: 450, y: 200 } },
  },
  {
    id: 'arden-demo',
    name: 'Simple Arden Demo',
    description: 'A simple DFA to demonstrate Arden\'s Theorem. Accepts (aa+b)a*.',
    acceptedExamples: ['b', 'aa', 'ba', 'aaa', 'baa'],
    rejectedExamples: ['a', 'ab', 'bb', 'aba'],
    automaton: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      startState: 'q0',
      finalStates: ['q2'],
      transitions: [
        { from: 'q0', to: 'q1', symbol: 'a' },
        { from: 'q0', to: 'q2', symbol: 'b' },
        { from: 'q1', to: 'q2', symbol: 'a' },
        { from: 'q2', to: 'q2', symbol: 'a' },
      ],
    },
    positions: { q0: { x: 100, y: 200 }, q1: { x: 350, y: 100 }, q2: { x: 600, y: 200 } },
  },
  {
    id: 'binary-div-2',
    name: 'Binary divisible by 2',
    description: 'Accepts binary strings representing numbers divisible by 2.',
    acceptedExamples: ['0', '10', '100', '110'],
    rejectedExamples: ['1', '11', '101', '111'],
    automaton: {
      states: ['q0', 'q1'],
      alphabet: ['0', '1'],
      startState: 'q0',
      finalStates: ['q0'],
      transitions: [
        { from: 'q0', to: 'q0', symbol: '0' },
        { from: 'q0', to: 'q1', symbol: '1' },
        { from: 'q1', to: 'q0', symbol: '0' },
        { from: 'q1', to: 'q1', symbol: '1' },
      ],
    },
    positions: { q0: { x: 150, y: 200 }, q1: { x: 450, y: 200 } },
  },
  {
    id: 'nfa-example',
    name: 'NFA Example',
    description: 'An NFA that accepts strings ending with "ab".',
    acceptedExamples: ['ab', 'aab', 'bab'],
    rejectedExamples: ['a', 'b', 'ba'],
    automaton: {
      states: ['q0', 'q1', 'q2'],
      alphabet: ['a', 'b'],
      startState: 'q0',
      finalStates: ['q2'],
      transitions: [
        { from: 'q0', to: 'q0', symbol: 'a' },
        { from: 'q0', to: 'q0', symbol: 'b' },
        { from: 'q0', to: 'q1', symbol: 'a' },
        { from: 'q1', to: 'q2', symbol: 'b' },
      ],
    },
    positions: { q0: { x: 100, y: 200 }, q1: { x: 350, y: 200 }, q2: { x: 600, y: 200 } },
  },
];
